import { useEffect, useState } from 'react'
import './App.css'

const fallbackContent = {
  cities: 6, stores: 185, garments: '350K',
  services: ['Dry cleaning', 'Laundry', 'Steam press', 'Shoe care'],
  sigma: ['Unique barcode tags', 'Specialised segregation', 'Wash care instructions', 'Fabric-friendly detergents', 'Steam press', 'Three-stage quality check'],
}
const garmentTypes = [
  ['Shirts', 'shirt.jpg'], ['Trousers', 'trousers.jpg'], ['Lehengas', 'lehenga.jpg'], ['Sarees', 'saree.jpg'],
]

function App() {
  const [content, setContent] = useState(fallbackContent)
  const [menuOpen, setMenuOpen] = useState(false)
  const [bookingOpen, setBookingOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [selectedService, setSelectedService] = useState('Dry cleaning')
  useEffect(() => {
    fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:4000'}/api/site-content`).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => setContent({ ...fallbackContent, ...data })).catch(() => {})
  }, [])
  const openBooking = (service = 'Dry cleaning') => { setSelectedService(service); setSubmitted(false); setBookingOpen(true) }
  const submitBooking = async (event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:4000'}/api/pickups`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(formData)) }); if (response.ok) setSubmitted(true) }

  return <div className="site-shell">
    <header className="site-header"><a className="logo" href="#top"><span>C</span><strong>cleaning<span>squad</span></strong></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button><nav className={menuOpen ? 'site-nav open' : 'site-nav'}><a href="#services">Services</a><a href="#how-it-works">How it works</a><a href="#sigmacare">Care process</a><a href="#garments">Garments</a><a href="/fabricspa.com/our-stores/">Our stores</a><button className="nav-cta" onClick={() => openBooking()}>Book a pickup <span>↗</span></button></nav></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="kicker">KENYA'S LARGEST DRY CLEANING & LAUNDRY CHAIN</p><h1>Fresh clothes.<br /><em>Fresh feeling.</em></h1><p className="hero-text">Professional fabric care, picked up from your doorstep and returned with a little more love.</p><button className="button dark" onClick={() => openBooking()}>Schedule a pickup <span>↗</span></button><div className="hero-note"><span>✦</span> Free doorstep pickup and delivery</div></div><div className="hero-visual"><img src="/fabricspa.com/wp-content/uploads/2026/01/website-banners-08.jpg" alt="Freshly cared for clothes" /><div className="floating-card"><strong>9-step</strong><span>SigmaCare™ process</span></div></div></section>
      <section className="trust-strip"><p>INDIA'S FINEST FABRIC AND GARMENT CARE SERVICE</p><div><strong>16</strong><span>years of care</span></div><div><strong>{content.cities}</strong><span>states served</span></div><div><strong>{content.stores}+</strong><span>stores across India</span></div><div><strong>{content.garments}</strong><span>garments monthly</span></div></section>
      <section className="intro section"><div className="section-label">01 / WHAT WE DO</div><div className="intro-grid"><h2>Your precious garments,<br /><em>our devoted care.</em></h2><div><p>We handle couture, heirlooms and your most treasured garments. Whether it is a cherished saree, a wedding lehenga, or your favourite designer outfit, we treat every garment with the care it deserves.</p><a className="arrow-link" href="/fabricspa.com/about-us/">Our story <span>↗</span></a></div></div></section>
      <section className="services section" id="services"><div className="section-label">02 / OUR SERVICES</div><div className="section-heading"><h2>Care<br /><em>your way.</em></h2><p>Every garment. Every detail. Every time. Choose the service that fits your life.</p></div><div className="service-grid">{content.services.map((service, index) => <article className="service-card" key={service}><span className="service-number">0{index + 1}</span><div className={`service-art art-${index + 1}`}><span>{['◌', '⌁', '≋', '◇'][index]}</span></div><h3>{service}</h3><p>{['Gentle care for everyday and occasion wear.', 'Wash, fold and finish, just the way you like it.', 'Crisp, crease-free clothes ready when you are.', 'Expert care for shoes, bags and accessories.'][index]}</p><button onClick={() => openBooking(service)}>Book this service <span>↗</span></button></article>)}</div></section>
      <section className="split-section" id="how-it-works"><div className="split-image"><img src="/fabricspa.com/wp-content/uploads/2025/07/work-img-1.jpg" alt="Cleaning Squad pickup and delivery" /></div><div className="split-copy"><div className="section-label">03 / HOW IT WORKS</div><h2>Clean clothes,<br /><em>zero effort.</em></h2><div className="steps"><Step number="01" title="Schedule online" text="Choose pickup and drop-off times that work best for you." /><Step number="02" title="We pick up" text="A Cleaning Squad agent collects your clothes from your doorstep." /><Step number="03" title="We deliver" text="Your clothes return clean, fresh and wrinkle-free." /></div><button className="button outline" onClick={() => openBooking()}>Start with a pickup <span>↗</span></button></div></section>
      <section className="care-section section"><div className="section-label">04 / CARE THAT FITS YOU</div><h2>Because every garment<br /><em>has its own story.</em></h2><div className="care-grid"><Care title="Regular" text="Thoughtful care, right on time. Everyday garments handled with signature attention." image="care-img-1.svg" /><Care title="Express" text="When you need it fresh, fast and flawless, for life's last-minute plans." image="care-img-2.svg" /><Care title="Premium" text="For garments that cannot afford shortcuts. Reserved for your most prized pieces." image="care-img-3.svg" /></div></section>
      <section className="sigma section" id="sigmacare"><div className="section-label">05 / THE CLEANING SQUAD DIFFERENCE</div><div className="sigma-head"><h2>Experience the nuances of<br /><em>9-step care</em></h2><p>A considered process built around your clothes, so they look better and feel better for longer.</p></div><div className="sigma-list">{content.sigma.map((step, index) => <div key={step}><strong>0{index + 1}</strong><span>{step}</span></div>)}</div></section>
      <section className="garments section" id="garments"><div className="section-label">06 / WE CARE BY THE PIECE</div><div className="section-heading"><h2>From head to toe,<br /><em>we have you covered.</em></h2><p>Expert treatment for clothes and accessories across every part of your wardrobe.</p></div><div className="garment-grid">{garmentTypes.map(([name, image]) => <button className="garment-card" key={name} onClick={() => openBooking(name)}><img src={`/fabricspa.com/wp-content/uploads/2025/08/${image}`} alt={name} /><span>{name}</span><small>Explore care ↗</small></button>)}</div></section>
      <section className="quote-section"><p>“We do not deal in loads.”</p><h2>We care<br /><em>by the piece.</em></h2><span>Thousands of customers trust us with their most-loved clothes.</span></section>
      <section className="app-banner"><div><p className="kicker">YOUR CLOSET, IN YOUR POCKET</p><h2>More care.<br /><em>One tap away.</em></h2><p>Book pickups, track orders and find your nearest Cleaning Squad store on the app.</p><button className="button light" onClick={() => openBooking()}>Get started <span>↗</span></button></div><img src="/fabricspa.com/wp-content/uploads/2025/09/app-mob-img-1.png" alt="Cleaning Squad mobile app" /></section>
    </main>
    <footer className="site-footer"><a className="logo" href="#top"><span>C</span><strong>cleaning<span>squad</span></strong></a><p>Because clothes carry more than just a story.</p><div className="footer-links"><a href="/fabricspa.com/about-us/">About us</a><a href="/fabricspa.com/privacy-policy/">Privacy</a><a href="/fabricspa.com/terms-condition/">Terms</a><a href="/fabricspa.com/contact-us/">Contact</a></div><div className="contact-details"><a href="tel:+254708309425">+254 708 309425</a><a href="mailto:safisquaadcleaningservices@gmail.com">safisquaadcleaningservices@gmail.com</a></div><small>© {new Date().getFullYear()} Safi Squad Cleaning Services Limited.</small></footer>
    {bookingOpen && <div className="modal-backdrop" onClick={() => setBookingOpen(false)}><div className="booking-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setBookingOpen(false)} aria-label="Close">×</button>{submitted ? <div className="success"><span>✓</span><h2>Pickup request received.</h2><p>Our care team will call you shortly to confirm your {selectedService.toLowerCase()} pickup.</p><button className="button dark" onClick={() => setBookingOpen(false)}>Done</button></div> : <><p className="kicker">DOORSTEP PICKUP</p><h2>Let us take care<br /><em>of the rest.</em></h2><form onSubmit={submitBooking}><label>Name<input required name="name" placeholder="Your name" /></label><label>Phone<input required name="phone" type="tel" placeholder="10-digit mobile number" /></label><label>Service<select value={selectedService} onChange={(event) => setSelectedService(event.target.value)}>{content.services.map((service) => <option key={service}>{service}</option>)}</select></label><label>Pickup area<input required name="area" placeholder="City or neighbourhood" /></label><button className="button dark" type="submit">Request a pickup <span>↗</span></button></form></>}</div></div>}
  </div>
}

function Step({ number, title, text }) { return <div className="step"><strong>{number}</strong><div><h3>{title}</h3><p>{text}</p></div></div> }
function Care({ title, text, image }) { return <article className="care-card"><img src={`/fabricspa.com/wp-content/uploads/2025/07/${image}`} alt="" /><h3>{title}</h3><p>{text}</p><a href="/fabricspa.com/contact-us/">Choose {title.toLowerCase()} <span>↗</span></a></article> }
export default App
